name: vuepress-deploy
displayName: 'vuepress-deploy'
triggers:
  push:
    - matchType: PRECISE
      branch: master
stages:
  - stage:
      name: npm-build-stage
      displayName: 'npm Stage'
      failFast: true
      steps:
        - step: npmbuild@1
          name: build and deploy
          displayName: 'npm Step'
          inputs:
            nodeVersion: 14.15
            goals: |
                yarn config set registry https://r.npm.taobao.org
                yarn
                yarn build
                cd src/.vuepress/
                rm -rf gh-pages
                mkdir -p ~/.ssh/
                echo "${ACTION_DEPLOY_KEY}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan gitee.com >> ~/.ssh/known_hosts
                git clone -q --depth=1 -b gh-pages "${ACCESS_ORIGIN}" gh-pages
                cd gh-pages
                git config user.name "${ACCESS_NAME}"
                git config user.email "${ACCESS_EMAIL}"
                rm -rf *
                cp -a ../dist/* .
                git add -A
                git commit -q -m "Auto Deploy from Github Actions: $(date +"%Y年%m月%d日 %T %:z")"
                git push -q
                rm -rf ~/.ssh/*