name: vuepress-deploy
displayName: "vuepress-deploy"
triggers:
  push:
    - matchType: PRECISE
      branch: master
stages:
  - stage:
      name: npm-build-stage
      displayName: "npm Stage"
      failFast: true
      steps:
        - step: npmbuild@1
          name: build and deploy
          displayName: "npm Step"
          inputs:
            nodeVersion: 14.15
            goals: |
              yarn
              yarn build
              cd src/.vuepress/dist
              git config --global init.defaultBranch master
              git init
              git config user.name "${ACCESS_NAME}"
              git config user.email "${ACCESS_EMAIL}"
              git remote add origin "https://${ACCESS_NAME}:${ACCESS_TOKEN}@gitee.com/qcyblm/qcyblm.git"
              git add -A
              git commit -q -m "Auto Deploy from Gitee Go: $(date +"%Y-%m-%d %H:%M")"
              git push -f origin master:gh-pages
