name: baiduPush
on:
  schedule:
    - cron: '30 0,13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'baiduPush'
      - name: Baidu Push
        run: |
          date
          curl -H 'Content-Type:text/plain' --data-binary @urls.txt "${{ secrets.BAIDU_TOKEN }}"
