name: Git Mirror Action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'master'
          persist-credentials: false
          fetch-depth: 0
        env:
          TZ: Asia/Shanghai
      - run: |
          date > generated.txt
          git config user.name qcyblm
          git config user.email ${{ secrets.GIT_EMAIL }}
          git remote add gitee https://gitee.com/qcyblm/qcyblm.git
          git remote add coding https://e.coding.net/qcyblm/qcyblm.git
          git fetch -q --all
          git push -q https://qcyblm:${{ secrets.GITEE_TOKEN }}@gitee.com/qcyblm/qcyblm.git master
          git push -q https://${{ secrets.CODING_TOKEN_NAME }}:${{ secrets.CODING_TOKEN }}@e.coding.net/qcyblm/qcyblm.git master
