name: Mirror Github to Gitee
on:
  push:
    branches:
      - master
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'master'
          persist-credentials: false
          fetch-depth: 0
        env:
          TZ: Asia/Shanghai
      - name: Mirror Github to Gitee
        run: |
          git remote add gitee https://gitee.com/qcyblm/qcyblm.git
          git fetch --all
          git push https://qcyblm:${{ secrets.GITEE_TOKEN }}@gitee.com/qcyblm/qcyblm.git master
          
          
