name: vuepress-deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.*/**/*'
      - '.*'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['lts/fermium']
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'master'
          persist-credentials: false
          fetch-depth: 0
        env:
          TZ: Asia/Shanghai
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Handle yarn cache
        uses: actions/cache@main
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn
      - name: Build VuePress
        run: yarn docs:build
      - name: Deploy to Pages
        env:
         TZ: Asia/Shanghai
        run: |
         cd docs/.vuepress/dist
         git config --global init.defaultBranch master
         git init
         git config user.name "qcyblm"
         git config user.email "qcyblm@139.com"
         git add .
         git commit -q -m "Deploying to gh-pages from @ $GITHUB_SHA in $(date +"%Y年%m月%d日 %T %Z")"
         git push -f -q https://$GITHUB_ACTOR:${{ github.token }}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
         git push -f -q https://$GITHUB_ACTOR:${{ secrets.GITEE_TOKEN }}@gitee.com/qcyblm/qcyblm.git master:gh-pages
      - name: Gitee Pages Action
        uses: yanglbme/gitee-pages-action@v1.2.8
        with:
          gitee-username: qcyblm
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: qcyblm/qcyblm
          branch: gh-pages
          https: true
          
